---
name: codecov
on:
  push:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          tooken: ${{ secrets.CODECOV_TOKEN }}
          toolchain: stable
          override: true
      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
